### ISSUE TITLE
ipfs-cohost - a cli to cohost sites on IPFS

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/cohosting#1]
It's a thing https://github.com/olizilla/ipfs-cohost

> If your domain has a DNSlink to a CID, then `ipfs-cohost` will let others pin it to their IPFS node.

**Comment by lidel** [comment]
Yes! The idea here is to switch it from `pin` API to MFS-based spec proposed in #2  (added `ipfs-cohost` to "Implementations" there)

It would enable people to use MFS for managing cohosted snapshots and share the list of cohosted websites between `ipfs-cohost` and `ipfs-companion`

**Comment by hacdias** [comment]
Updates on this:

- https://github.com/olizilla/ipfs-cohost/issues/4
- https://github.com/olizilla/ipfs-cohost/pull/5
