### ISSUE TITLE
Rename `gc` to something else 

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/cohosting#8]
We should rename `gc` operation to something else to avoid confustion with `ipfs gc` command.

How about `prune` ?

[![Screenshot_2019-10-24 prune - Wiktionary](https://user-images.githubusercontent.com/157609/67502587-627e3680-f686-11e9-95f9-55cdeef98344.png)](https://en.wiktionary.org/wiki/prune#Etymology_2)

**Comment by hacdias** [comment]
Agreed! Prune is a simple term and I believe it's suitable for the case.

**Comment by hacdias** [comment]
Actually, I just noticed this is not on the SPEC. Perhaps we should add it.

**Comment by lidel** [comment]
Yes, I created this issue to remember to update/add it everywhere :+1:
